"""Add created_at column to all models

Revision ID: 0da54e0d9fb8
Revises: 9a33f0f0c84c
Create Date: 2025-05-27 20:51:04.893129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da54e0d9fb8'
down_revision: Union[str, None] = '9a33f0f0c84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_authors_id', table_name='authors')
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_books_id', table_name='books')
    op.add_column('genres', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_genres_id', table_name='genres')
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_tags_id', table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.drop_column('tags', 'created_at')
    op.create_index('ix_genres_id', 'genres', ['id'], unique=False)
    op.drop_column('genres', 'created_at')
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.drop_column('books', 'created_at')
    op.create_index('ix_authors_id', 'authors', ['id'], unique=False)
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###
