"""Add timestamps

Revision ID: f409801501d9
Revises: 9a33f0f0c84c
Create Date: 2025-05-26 21:39:15.128545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f409801501d9'
down_revision: Union[str, None] = '9a33f0f0c84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    op.add_column('authors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('authors', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_authors_id', table_name='authors')
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_books_id', table_name='books')
    op.add_column('genres', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('genres', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_genres_id', table_name='genres')
    op.add_column('tags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_tags_id', table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.create_index('ix_genres_id', 'genres', ['id'], unique=False)
    op.drop_column('genres', 'updated_at')
    op.drop_column('genres', 'created_at')
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    op.create_index('ix_authors_id', 'authors', ['id'], unique=False)
    op.drop_column('authors', 'updated_at')
    op.drop_column('authors', 'created_at')
    op.create_table('book_genre',
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    # ### end Alembic commands ###
